"""empty message

Revision ID: 28f829debb15
Revises: 
Create Date: 2021-01-22 20:21:52.487079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28f829debb15'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('username', sa.String(length=40), nullable=True),
    sa.Column('image_url', sa.String(length=256), nullable=True),
    sa.Column('profile_url', sa.String(length=256), nullable=True),
    sa.Column('type', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
